### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/learn-build-teach-discord-bot#10]
We should add ESLint for consistency in the code as more people contribute.

**Comment by advaith-unnikrishnan** [comment]
Hey @jamesqquick  I would like to work on this issue

**Comment by jamesqquick** [comment]
Awesome. Just assigned you!

**Comment by advaith-unnikrishnan** [comment]
Hey @jamesqquick  could you kindly review the pull request
