### ISSUE TITLE
Prevent Content Embeds on Profile Listing

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/learn-build-teach-discord-bot#11]
The /profile command includes links to the user's Twitter, YouTube, etc. The problem is that is shows content embeds for each one making the profile data very long. We should prevent it from listing the embeds to make the information much shorter.

![CleanShot 2021-10-02 at 17 42 21](https://user-images.githubusercontent.com/5391915/135733517-2d1327a2-4885-471d-9975-47bb79ca1b62.jpg)

**Comment by DenysLins** [comment]
@jamesqquick, I will implement this enhancement.
