### ISSUE TITLE
Remove kudo if reaction removed

### ISSUE THREAD

**Issue by mhuggins7278** [Learn-Build-Teach/learn-build-teach-discord-bot#33]
If a user reacts to a message with the "learn", "build" or "teach" reactions the bot will give the author of the message a kudo. 

If the user removes said reaction we should probably also try to remove the kudo

## Questions
- [ ] What event from discord do we hook into
- [ ] how do we know what kudo to remove. 
- [ ] should we add a messageId field to the kudo schema (would make it easier to remove the correct kudo)
- [ ] are we ok just removing the most recent kudo given by the user to the message author

**Comment by jamesqquick** [comment]
I wondered about that. My thought is we wouldn't need to. Nothing wrong with having extra kudos?

**Comment by mhuggins7278** [comment]
Yeah totally not only that but it might prove to be more of a hassle than it's really worth

**Comment by mhuggins7278** [comment]
going to close this for now extra kudos don't hurt :-)
