### ISSUE TITLE
Kudo's leaderboard endpoint

### ISSUE THREAD

**Issue by mhuggins7278** [Learn-Build-Teach/learn-build-teach-discord-bot#34]
We've had some basic discussion on showing a leaderboard for Kudos.

Just a couple of thoughts on how to best do it. 
We could write some queries that do the aggregation using something like this.
https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#group-by
Or we could just return all the records from prisma and do it in JS
From past experiences doing it in code vs the DB is way more performant. Although give our data size it may not matter either way

**Comment by jamesqquick** [comment]
Yes, love this!

**Comment by mhuggins7278** [comment]
done
