### ISSUE TITLE
Inconsistent Twitter Usernames and Links in User Profiles

### ISSUE THREAD

**Issue by max-programming** [Learn-Build-Teach/learn-build-teach-discord-bot#77]
Some profiles have their Twitter usernames 
![image](https://user-images.githubusercontent.com/51731966/216657873-286f3fea-5a5b-4476-b0d3-fdfc9c3cf026.png)

And some profiles have their Twitter links
![image](https://user-images.githubusercontent.com/51731966/216657957-5dfc32be-978f-46f6-a47f-b2516bd391f9.png)

This causes problems when sharing content because the people don't get mentioned properly. [Their URLs get mentioned](https://twitter.com/search?q=from%3Ajamesqquick%20%40https%3A%2F%2F&src=typed_query)

**Comment by jamesqquick** [comment]
Just fixed!!
