### ISSUE TITLE
Displaying User ID Instead of Username

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/learn-build-teach-discord-bot#8]
The /profile command should display the username of the user instead of their Discord ID.

![CleanShot 2021-10-02 at 17 33 58](https://user-images.githubusercontent.com/5391915/135733391-17f472df-3e6a-4158-9820-96763638b5ec.jpg)

**Comment by DenysLins** [comment]
Can I work on that?

**Comment by jamesqquick** [comment]
@DenysLins go for it! Are you able to assign it to yourself?

**Comment by jamesqquick** [comment]
Just assigned it to you!
